deployment:
  tasks:
    # Deploy your Next.js application
    - export DEPLOYPATH=/home/zerocom/new.zero-31.com/
    - /bin/rm -rf $DEPLOYPATH/* # Clear previous deployment
    - /bin/cp -R * $DEPLOYPATH

    - /bin/cp .env.production $DEPLOYPATH
    - cd $DEPLOYPATH && npm install
    - cd $DEPLOYPATH && npm run build
