deployment:
  tasks:
    # Deploy your Next.js application
    - export DEPLOYPATH=/home/zerocom/new.zero-31.com/
    #- /bin/rm -rf $DEPLOYPATH/* # Clear previous deployment
    - /bin/cp -R * $DEPLOYPATH
    # copy env production to .env
    #- /bin/cp .env.production $DEPLOYPATH.env
