deployment:
  tasks:
    # Deploy your Next.js application
    - export DEPLOYPATH=/home/zerocom/repositories/zero31/
    - /bin/cp -R .next $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R package.json $DEPLOYPATH
    - /bin/cp -R node_modules $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
    - /bin/cp .env.production $DEPLOYPATH
